import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { describeApiFailure } from "../../api/apiError";
import { BrandHeader, Button, Notice, Screen, sharedStyles } from "../../components/ui";
import { colors, spacing } from "../../components/theme";
import { getPublicCleanupEvent, listPublicCleanupEvents } from "./cleanupEvent.api";
import type { CleanupEventPublicDetail, CleanupEventPublicSummary } from "./cleanupEvent.types";

export function PublicCleanupEventsScreen({ accessToken, onBack }: { accessToken: string; onBack: () => void }) {
  const [items, setItems] = useState<CleanupEventPublicSummary[]>([]); const [selected, setSelected] = useState<CleanupEventPublicDetail>(); const [nextCursor, setNextCursor] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState<string>();
  const load = useCallback(async (cursor?: string) => { setBusy(true); setError(undefined); try { const page = await listPublicCleanupEvents(accessToken, cursor); setItems((current) => cursor ? [...current, ...page.items] : page.items); setNextCursor(page.nextCursor); } catch (reason) { setError(describeApiFailure(reason, "Unable to load cleanup events.").message); } finally { setBusy(false); } }, [accessToken]);
  useEffect(() => { void load(); }, [load]);
  async function open(id: string): Promise<void> { setBusy(true); setError(undefined); try { setSelected(await getPublicCleanupEvent(accessToken, id)); } catch (reason) { setError(describeApiFailure(reason, "Unable to load event details.").message); } finally { setBusy(false); } }
  return <Screen><BrandHeader eyebrow="Community cleanups" title="Published events" subtitle="Verified schedules and volunteer instructions" compact />{error ? <Notice tone="error" message={error} /> : null}{selected ? <View style={[sharedStyles.card, styles.detail]}><Text style={styles.status}>{selected.lifecycleStatus.replaceAll("_", " ")}</Text><Text style={sharedStyles.sectionTitle}>{selected.title}</Text><Text style={styles.organization}>{selected.organization.name}</Text><Text style={styles.copy}>{selected.description}</Text><Text style={styles.heading}>VOLUNTEER INSTRUCTIONS</Text><Text style={styles.copy}>{selected.publicInstructions}</Text><Text style={styles.heading}>LOCATION</Text><Text style={styles.copy}>{selected.meetingAddress || selected.eventAddress || `${selected.eventLatitude}, ${selected.eventLongitude}`}</Text><Text style={styles.heading}>SESSIONS</Text>{selected.sessions.map((session) => <View key={session.id} style={styles.session}><Text style={styles.organization}>{session.sessionDate} · {session.startTime.slice(0, 5)}–{session.endTime.slice(0, 5)}</Text><Text style={styles.copy}>{session.locationAddress || "Event location"} · {session.capacity ?? "Open"} capacity</Text></View>)}<Notice message="Joining and availability will be added in EVT-04." /><Button label="Back to event list" variant="secondary" onPress={() => setSelected(undefined)} /></View> : <View style={sharedStyles.card}><Text style={sharedStyles.sectionTitle}>Upcoming and active events</Text>{busy && items.length === 0 ? <Text style={styles.copy}>Loading events…</Text> : items.length === 0 ? <Text style={styles.copy}>No published events yet.</Text> : items.map((item) => <Pressable key={item.id} onPress={() => void open(item.id)} style={styles.item}><View style={styles.flex}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.copy}>{item.organization.name}</Text><Text style={styles.meta}>{item.lifecycleStatus.replaceAll("_", " ")}</Text></View><Text style={styles.arrow}>→</Text></Pressable>)}{nextCursor ? <Button label="Load more" variant="secondary" loading={busy} onPress={() => void load(nextCursor)} /> : null}</View>}<Button label="Citizen dashboard" variant="secondary" onPress={onBack} /></Screen>;
}

const styles = StyleSheet.create({ detail: { borderColor: colors.primary }, status: { alignSelf: "flex-start", paddingHorizontal: spacing.sm, paddingVertical: 4, borderRadius: 999, backgroundColor: colors.successSoft, color: colors.success, fontSize: 11, fontWeight: "900" }, organization: { color: colors.text, fontWeight: "800" }, copy: { color: colors.textMuted, fontSize: 13, lineHeight: 19 }, heading: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1, marginTop: spacing.sm }, session: { gap: 3, paddingVertical: spacing.sm, borderTopWidth: 1, borderTopColor: colors.border }, item: { flexDirection: "row", alignItems: "center", paddingVertical: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, flex: { flex: 1, gap: 3 }, itemTitle: { color: colors.text, fontSize: 16, fontWeight: "900" }, meta: { color: colors.primary, fontSize: 11, fontWeight: "900" }, arrow: { color: colors.primary, fontSize: 24 } });
