import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { describeApiFailure } from "../../../api/apiError";
import { colors, spacing } from "../../../components/theme";
import { getAdministrativeAreaBoundary, listAdministrativeAreas } from "../../organizations/organizationApplication.api";
import type { AdministrativeArea } from "../../organizations/organizationApplication.types";
import type { MapBoundaryFeatureCollection } from "../map.types";
export function AdministrativeAreaMapSearch({ accessToken, onBoundaryChange }: { accessToken: string; onBoundaryChange: (boundary: MapBoundaryFeatureCollection | undefined) => void }) {
  const [query, setQuery] = useState(""); const [areas, setAreas] = useState<AdministrativeArea[]>([]); const [error, setError] = useState<string>();
  useEffect(() => { if (query.trim().length < 2) { setAreas([]); return; } let active = true; const timeout = setTimeout(() => { void listAdministrativeAreas(accessToken, query).then((value) => { if (active) setAreas(value.slice(0, 8)); }).catch((reason) => { if (active) setError(describeApiFailure(reason, "Unable to search GN Divisions.").message); }); }, 300); return () => { active = false; clearTimeout(timeout); }; }, [accessToken, query]);
  async function select(area: AdministrativeArea) { try { const boundary = await getAdministrativeAreaBoundary(accessToken, area.id); onBoundaryChange({ type: "FeatureCollection", truncated: false, features: boundary.features.map((feature) => ({ type: "Feature", geometry: feature.geometry as MapBoundaryFeatureCollection["features"][number]["geometry"], properties: { id: feature.properties.id, name: feature.properties.name, officialCode: feature.properties.officialCode, status: "ACTIVE" } })) }); setQuery(area.name); setAreas([]); setError(undefined); } catch (reason) { setError(describeApiFailure(reason, "Unable to load this boundary.").message); } }
  return <View style={styles.shell}><Text style={styles.label}>Find a GN Division</Text><TextInput style={styles.input} value={query} onChangeText={(value) => { setQuery(value); onBoundaryChange(undefined); }} placeholder="GN Division, DS Division, district, or code" />{error ? <Text style={styles.error}>{error}</Text> : null}{areas.map((area) => <Pressable key={area.id} style={styles.result} onPress={() => void select(area)}><Text style={styles.title}>{area.name}</Text><Text style={styles.meta}>{[area.divisionalSecretariatName, area.districtName, area.officialCode].filter(Boolean).join(" · ")}</Text></Pressable>)}</View>;
}
const styles = StyleSheet.create({ shell: { gap: spacing.xs }, label: { color: colors.text, fontWeight: "800" }, input: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: spacing.sm, color: colors.text, backgroundColor: colors.surface }, result: { padding: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, title: { color: colors.text, fontWeight: "800" }, meta: { color: colors.textMuted, fontSize: 12 }, error: { color: colors.danger } });
