const { withAppBuildGradle } = require("expo/config-plugins");

const marker = "// @generated by EcoTrack short Android CMake path plugin";
const gradleBlock = `

${marker}
if (System.getProperty("os.name").toLowerCase().contains("windows")) {
    def ecoTrackNativeBuildDirectory =
        System.getenv("ECOTRACK_ANDROID_CXX_DIR") ?: "C:/ecotrack-android-cxx"
    println "[EcoTrack] Native CMake staging: \${ecoTrackNativeBuildDirectory}"
    android {
        externalNativeBuild {
            cmake {
                buildStagingDirectory ecoTrackNativeBuildDirectory
            }
        }
    }
}
`;

module.exports = function withShortAndroidCmakePath(config) {
  return withAppBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.language !== "groovy") {
      throw new Error("EcoTrack's Android CMake path plugin requires Groovy build.gradle output.");
    }

    if (!modConfig.modResults.contents.includes(marker)) {
      modConfig.modResults.contents = `${modConfig.modResults.contents.trimEnd()}${gradleBlock}`;
    }

    return modConfig;
  });
};
